create use context data
IngridC10/budget_manager pull request #3
Opened 2024-06-13 04:30 UTC by IngridC10

-Create category context data and use it in KanbanBoardComponent.

2024-06-17 17:29 UTC, harolCalzada requested changes

2024-06-17 17:29 UTC, harolCalzada commented on app/layout.tsx
> +          {" "}
esto para que sirve?

2024-06-17 17:29 UTC, harolCalzada commented on app/providers/CategoryProviders.tsx
> +import React, { createContext, useState, ReactNode } from "react"; // Ajusta la ruta de importación según sea necesario
este comentario es necesario ?

2024-06-17 17:29 UTC, harolCalzada commented on app/providers/CategoryProviders.tsx
> +  categoriesState: Category[]; // Cambia 'any' al tipo específico para tus categorías
este comentario es necesario ?

2024-06-17 17:29 UTC, harolCalzada commented on components/IconsNewCategoryListComponent.tsx
> +import IconsNewCategoryListData from "@/data/IconsNewCategoryListData"; // Ajusta la ruta de importación según sea necesario
este comentario es necesario ?

2024-06-17 17:29 UTC, harolCalzada commented on components/IconsNewCategoryListComponent.tsx
> +  // Organiza los íconos por categorías
si este comentario es necesario ponerlo en ingles

2024-06-17 17:29 UTC, harolCalzada commented on components/IconsNewCategoryListComponent.tsx
> +      {/* Renderiza las categorías dinámicamente */}
si este comentario es necesario ponerlo en ingles

2024-06-17 17:47 UTC, IngridC10 commented on app/providers/CategoryProviders.tsx
> +import React, { createContext, useState, ReactNode } from "react"; // Ajusta la ruta de importación según sea necesario
ok! ya esta corregido

2024-06-17 18:22 UTC, IngridC10 commented on app/layout.tsx
> +          {" "}
Si ya se elimino porque no tenia ninguna funcionalidad.

2024-06-17 18:22 UTC, IngridC10 commented on app/providers/CategoryProviders.tsx
> +  categoriesState: Category[]; // Cambia 'any' al tipo específico para tus categorías
no no es necesario, ya se elimino

2024-06-17 18:22 UTC, IngridC10 commented on components/IconsNewCategoryListComponent.tsx
> +import IconsNewCategoryListData from "@/data/IconsNewCategoryListData"; // Ajusta la ruta de importación según sea necesario
no no es necesario, ya se elimino

2024-06-17 18:22 UTC, IngridC10 commented on components/IconsNewCategoryListComponent.tsx
> +  // Organiza los íconos por categorías
ok

2024-06-17 18:22 UTC, IngridC10 commented on components/IconsNewCategoryListComponent.tsx
> +      {/* Renderiza las categorías dinámicamente */}
ok

2024-06-17 20:31 UTC, harolCalzada requested changes

2024-06-17 20:31 UTC, harolCalzada commented on app/page.tsx
> +              {" "}
este sirve para algo ?

2024-06-17 20:31 UTC, harolCalzada commented on components/IconsNewCategoryListComponent.tsx
> +    console.log(`Categoría seleccionada: ${category}`);
remover console log

2024-06-17 20:31 UTC, harolCalzada commented on app/board/components/KanbanBoardComponent.tsx
> +  console.log("category state", categoriesState);
remover console logs

2024-06-18 05:40 UTC, IngridC10 commented on app/board/components/KanbanBoardComponent.tsx
> +  console.log("category state", categoriesState);
ok

2024-06-18 05:40 UTC, IngridC10 commented on components/IconsNewCategoryListComponent.tsx
> +    console.log(`Categoría seleccionada: ${category}`);
ok

2024-06-18 05:40 UTC, IngridC10 commented on app/page.tsx
> +              {" "}
ok

2024-06-18 06:27 UTC, harolCalzadaZebrand approved these changes

2024-06-18 06:27 UTC, merged